# Generated by Django 3.1.2 on 2020-12-05 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationEmail',
            fields=[
                ('to_user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_expired', models.IntegerField()),
                ('random_string', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'activation_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('transactiontime', models.DateTimeField()),
                ('ordernumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'confirm_string',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Limitedtime',
            fields=[
                ('seller', models.CharField(max_length=200)),
                ('limitquantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('srcset', models.ImageField(upload_to='')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'limitedtime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainConfirmstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
                ('user_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'main_confirmstring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('srcset', models.CharField(max_length=1000)),
                ('sold', models.IntegerField()),
                ('money', models.IntegerField()),
                ('sell', models.CharField(max_length=1000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('ip', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=2000, null=True)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnippetsSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'snippets_snippet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key1', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'system_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Udn',
            fields=[
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('report', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('time', models.CharField(blank=True, max_length=2000, null=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'udn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed', models.IntegerField()),
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
