version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ~/data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      PGData: /var/lib/postgresql/data/PGData
  web:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_shop_web:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres        